# Generated by Django 5.0.6 on 2024-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
