# Generated by Django 5.0.6 on 2024-05-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_products_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
