# Generated by Django 5.0.6 on 2024-05-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_products_p_venta_sales_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_venta',
        ),
    ]
