# Generated by Django 5.0.6 on 2024-05-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_remove_products_p_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cantidad',
        ),
    ]
