# Generated by Django 5.0.6 on 2024-05-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_remove_products_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_mayor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
