# Generated by Django 5.0.6 on 2024-05-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_products_p_mayor_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='descuento',
        ),
    ]
