# Generated by Django 5.0.6 on 2024-05-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_remove_sales_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='descuento',
            field=models.FloatField(default=0),
        ),
    ]
