# Generated by Django 5.0.6 on 2024-05-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
