# Generated by Django 5.0.6 on 2025-01-17 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0019_color_size_alter_productfeature_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='feature_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posApp.productfeature'),
        ),
    ]
