# Generated by Django 5.0.6 on 2025-01-17 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0021_color_date_added_color_date_updated_color_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='size',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='size',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
