# Generated by Django 5.0.6 on 2025-01-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0023_products_image_alter_productfeature_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='posApp.products'),
        ),
    ]
