# Generated by Django 5.0.6 on 2025-01-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0025_paymenttype_sales_payment_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='posApp.paymenttype'),
        ),
    ]
