# Generated by Django 5.2.3 on 2025-06-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0026_alter_paymenttype_name_alter_sales_payment_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
    ]
