# Generated by Django 5.2.3 on 2025-06-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0028_sales_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='p_mayor',
            new_name='p_mayor_compra',
        ),
        migrations.AddField(
            model_name='products',
            name='p_mayor_venta',
            field=models.FloatField(default=0),
        ),
    ]
